name: Bessentials
version: '${project.version}'
main: priv.nils.plugins.Bessentials
api-version: '1.20'


commands:
  fly:
    description: toggles flight
  gamemode:
    description: sets your gamemode
    aliases: ["gm"]
  flyspeed:
    description: sets your flyspeed
    aliases: ["fs","fspeed"]
  suicide:
    description: kills you
    aliases: ["die"]
  beer:
    description: gives you beer
    aliases: ["bier"]
  feed:
    description: feeds you
    aliases: ["eat"]
  heal:
    description: heals you
